Portfolio popup
hiwina/Portfolio-Mobile-first-project pull request #13
Opened 2022-11-24 07:56 UTC by hiwina

2022-11-25 21:03 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hi @hiwina , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️Linters
✔️Descriptive commit messages
✔️Descriptive summary

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 21:03 UTC, tugsem commented on styles.css
> +}
- [ ] This pop-up window almost identical to the given design in figma. However, you need to apply the right paddings to your window as in the figma. Also, please remove vertical scrolling in this page to make it more professional.
figma design:
![image](https://user-images.githubusercontent.com/91486791/204053836-5d00a128-9bca-421c-aa93-0bc6975c29e4.png)
your design:
![image](https://user-images.githubusercontent.com/91486791/204053871-33309349-6d1d-4dc3-bd14-841fcb249931.png)

2022-11-25 21:03 UTC, tugsem commented on styles.css
> +  }
- [ ] Please align your button text to center using flexbox to match the given design:
yours: 
![image](https://user-images.githubusercontent.com/91486791/204054143-b44af577-086a-426d-a261-72e094bc9ee6.png)
figma:
![image](https://user-images.githubusercontent.com/91486791/204054203-d250de98-7bae-4428-95eb-bd0de312ad3e.png)

2022-11-25 21:03 UTC, tugsem commented on styles.css
> +
- [ ] Please give the true spacings around this image to match the figma design. Also, your close button is on the right place. But can't be seen clearly. Try to make it white and bolder so that user can see the button.
your design: 
![image](https://user-images.githubusercontent.com/91486791/204054490-413f65d9-b333-430f-9f7b-54918b8df1f2.png)
figma: 
![image](https://user-images.githubusercontent.com/91486791/204054408-2a3abd70-e983-42ee-9e83-2d4a969b9921.png)

2022-11-25 21:03 UTC, tugsem commented on menu.js
> +}
- [ ] Your close buttons are working but they have an issue that must be resolved: when you close it on mobile it's closing but it's still showing at the desktrop sizes. Kindly fix it to make it more functional.
https://app.flonnect.com/view/video/saranlitugsem/63812d20e746641a4b9fd658

2022-11-26 12:40 UTC, bienvenuushindi approved these changes
# Approved 👏  

## Hi @hiwina   👋, 

Well done implementing the requested changes 👏

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## [Optional] suggestions:

- [ ] You have submitted a project, that has an old README, kindly consider using the [new README template](https://github.com/microverseinc/readme-template) provided by microverse

<img src="https://user-images.githubusercontent.com/25227022/203916898-0c8eed13-d824-4a2d-9abf-09daabc2fd95.png">

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @bienvenuushindi  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-26 12:46 UTC, merged